# MYSQL2. Versions 8.0.35
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
